Add PowerShell snippets for postinstall
python-poetry/install.python-poetry.org pull request #22
Opened 2022-07-16 14:54 UTC by tats-u

https://github.com/python-poetry/poetry/issues/5915

This PR allows Windows users to activate `poery` command without forcing them to google how to do it.

2022-07-17 09:57 UTC, tats-u commented
`````
Poetry (1.1.14) is installed now. Great!
To get started you need Poetry's bin directory (C:\Users\runneradmin\AppData\Roaming\Python\Scripts) in your `PATH`
environment variable.
You can choose and execute one of the following commands in PowerShell:
A. Appends the bin directory to your user environment variable `PATH`:
```
[Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", "User") + ";C:\Users\runneradmin\AppData\Roaming\Python\Scripts", "User")
```
B. Tries to appends the bin directory to PATH every when you run PowerShell (>=6 recommended):
```
echo 'if (-not (Get-Command poetry -ErrorAction Ignore)) { $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Scripts" }' | Out-File -Append $PROFILE
```
Alternatively, you can call Poetry explicitly with `C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry`.
You can test that everything is set up by executing:
`poetry --version`
`````

2022-07-24 17:56 UTC, johnthagen commented
For reviewers, here is a useful StackOverflow answer on the subject: https://stackoverflow.com/a/257120

2022-07-24 18:10 UTC, johnthagen requested changes
[Disclaimer, not a Poetry dev]

First off, thank you for making this PR. I think this is an important step to easing new Windows users into Poetry.

My personal feedback is that we should try to keep this simpler. The installer already prints quite a lot of text and having multiple Powershell commands I think could overwhelm the target audience.

If we look at the Unix variant of this for inspiration, it is very simple:

```py
POST_MESSAGE_CONFIGURE_UNIX = """
Add `export PATH="{poetry_home_bin}:$PATH"` to your shell configuration file.
"""
```

I would recommend we shorten this message to:

```py
POST_MESSAGE_CONFIGURE_WINDOWS = """
Execute the following in Powershell:

[Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", "User") + ";{poetry_home_bin}", "User")
"""
```

2022-07-24 18:11 UTC, johnthagen commented
I tested Option A in this MR in a clean Windows 10 VM and it worked as expected. 🚀

2022-07-24 23:20 UTC, tats-u commented
Unix OSes have no choice other than editing profile files for their shells, so how to activate Poetry can be kept simple.

In contrast of this, Windows has the built-in manager of environment variables.
PowerShell and CMD have profiles like shells for Unix.
This is why 2 option can be provided for Windows.

2022-08-05 17:00 UTC, johnthagen commented
@neersighted Would you be willing to review this PR? I personally think it would be important before the upcoming 1.2 final release. ❤️

2024-11-20 14:42 UTC, abn requested changes

2024-11-20 16:34 UTC, abn commented on install-poetry.py
> +B. Tries to appends the bin directory to PATH every when you run PowerShell (>=6 recommended):
@tats-u think you missed this one :)

2024-11-21 12:50 UTC, merged